package com.bpcbt.demo.dao;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.bpcbt.demo.entity.Location;
import com.bpcbt.demo.mockdb.LocationDB;

/**
 * This is the Data Access Object(DAO) implementation to get list of locations.
 * 
 * @author Sudharma Subasinghe
 *
 */
@Repository
public class LocationDAOImpl implements LocationDAO {
	
	@Autowired
	private LocationDB locationDB;

	/**
	 * This method retrieves all the location records using the connection to the database.
	 * For the mock database purpose, it returns the list of location which is generated by
	 * the {@LocationDB} class.
	 */
	@Override
	public List<Location> getLocations() {
		List<Location> list = locationDB.getLocationList();
		return list;
	}

}
